services:

    postgres:
        image: postgres:16-alpine
        container_name: postgres
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - transcendence_net
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
            interval: 5s
            timeout: 3s
            retries: 10
    node:
        build: ./node
        container_name: node
        environment:
            NODE_ENV: production
            DB_NAME: ${POSTGRES_DB}
            DB_USER: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            JWT_SECRET: ${JWT_SECRET}
            DB_HOST: postgres
            DB_PORT: "5432"
        ports:
            - "8787:8787"
        networks:
            - transcendence_net
        restart: unless-stopped

    nginx:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        container_name: nginx
        depends_on:
            - node
        ports:
            - "8080:8080"
            - "4430:4430"
        environment:
            HOSTNAME: ${HOSTNAME}
            LAN_IP: ${LAN_IP}
        networks:
            - transcendence_net
        restart: unless-stopped

    adminer:
        image: adminer
        container_name: adminer
        ports:
            - "8081:8080"
        networks:
            - transcendence_net
        restart: unless-stopped


networks:
    transcendence_net:
        driver: bridge

volumes:
    pgdata: